export const ALL_PROFILE = 'ALL_PROFILE';
export const DETAIL_PROFILE = 'DETAIL_PROFILE';

export const FETCH_REQUEST_EDIT_PERSONAL_DATA = 'FETCH_REQUEST_EDIT_PERSONAL_DATA';
export const FETCH_REQUEST_EDIT_CONTACT_DATA = 'FETCH_REQUEST_EDIT_CONTACT_DATA';
export const FETCH_REQUEST_EDIT_EMPLOYMENT_DATA = 'FETCH_REQUEST_EDIT_EMPLOYMENT_DATA';
export const FETCH_REQUEST_PROFILES = 'FETCH_REQUEST_PROFILES';
export const FETCH_REQUEST_DETAIL_PROFILES = 'FETCH_REQUEST_DETAIL_PROFILE';

export const FETCH_RESOLVE_EDIT_CONTACT_DATA = 'FETCH_RESOLVE_EDIT_CONTACT_DATA';
export const FETCH_RESOLVE_EDIT_PERSONAL_DATA = 'FETCH_RESOLVE_EDIT_PERSONAL_DATA';
export const FETCH_RESOLVE_EDIT_EMPLOYMENT_DATA = 'FETCH_RESOLVE_EDIT_EMPLOYMENT_DATA';
export const FETCH_RESOLVE_PROFILES = 'FETCH_RESOLVE_PROFILES';
export const FETCH_RESOLVE_DETAIL_PROFILE = 'FETCH_RESOLVE_DETAIL_PROFILES';

export const UPDATE_STAFF_MEMBER_IN_PROFILES = 'UPDATE_STAFF_MEMBER_IN_PROFILES';

export const FETCH_RESOLVE_ERROR = 'FETCH_RESOLVE_ERROR';
export const FETCH_RESOLVE = 'FETCH_RESOLVE';
