export const ALL_PROFILE = 'ALL_PROFILE';
export const DETAIL_PROFILE = 'DETAIL_PROFILE';
export const FAIL_FETCH_REQUEST = 'FAIL_FETCH_REQUEST';
export const FAIL_FETCH_RESOLVE = 'FAIL_FETCH_RESOLVE';
