export const ALL_PROFILE = 'ALL_PROFILE';
export const DETAIL_PROFILE = 'DETAIL_PROFILE';

export const FETCH_REQUEST_PROFILES = 'FETCH_REQUEST_PROFILES';
export const FETCH_REQUEST_DETAIL_PROFILES = 'FETCH_REQUEST_DETAIL_PROFILE';

export const FETCH_RESOLVE_PROFILES = 'FETCH_RESOLVE_PROFILES';
export const FETCH_RESOLVE_DETAIL_PROFILE = 'FETCH_RESOLVE_DETAIL_PROFILES';

export const FETCH_RESOLVE_ERROR = 'FETCH_RESOLVE_ERROR';
export const FETCH_RESOLVE = 'FETCH_RESOLVE';
